### ISSUE TITLE
PDF Title has different name

### ISSUE THREAD

**Issue by mbtamuli** [iamShantanu101/Resume-CV#1]
The [PDF Title](https://github.com/iamShantanu101/Resume-CV/blob/master/cv-style.cls#L208) and [PDF Author](https://github.com/iamShantanu101/Resume-CV/blob/master/cv-style.cls#L209) needs to be changed.

**Comment by ishantanu** [comment]
Fixed [a16def0](https://github.com/iamShantanu101/Resume-CV/commit/a16def0623146f20fbc4c59db7451f65aba555b4)!
